# PROGRAMMING ASSIGNMENT 2
## LAGUNA, CARLVINZ E. 
### 2ECE-B
### SEPTEMBER 3, 2025

1. NORMALIZATION PROBLEM: Normalization is one of the most basic preprocessing techniques in
data analytics. This involves centering and scaling process. Centering means subtracting the data from the
mean and scaling means dividing with its standard deviation. Mathematically, normalization can be
expressed as:

    𝑍 = 𝑋 − 𝑥̅ / 𝜎

    In Python, element-wise mean and element-wise standard deviation can be obtained by using .mean() and
    .std() calls.

    In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized
    ndarray as **X_normalized.npy**

In [3]:
# Import numpy library as np
import numpy as np

# Create a random 5x5 ndarray with values between 0 and 1
X = np.random.rand(5, 5)

# Compute the mean of the array
mean_X = X.mean()

# Compute the standard deviation of the array
std_X = X.std()

# Normalize the array using the formula (X - mean) / std
X_normalized = (X - mean_X) / std_X

# Save the normalized array into a file named 'X_normalized.npy'
np.save("X_normalized.npy", X_normalized)

# Display the original 5x5 matrix
print("Original X:\n", X)

# Display the normalized 5x5 matrix
print("\nNormalized X:\n", X_normalized)

Original X:
 [[0.60047921 0.86820711 0.88491311 0.18954445 0.90453443]
 [0.67645823 0.34468817 0.33567531 0.44584136 0.20945855]
 [0.84224112 0.89349545 0.55048818 0.67381018 0.30297343]
 [0.5146586  0.95787808 0.63488591 0.99979578 0.12894773]
 [0.8391685  0.56148971 0.79566032 0.05292669 0.67717269]]

Normalized X:
 [[ 0.01840392  0.99149141  1.05221126 -1.47518515  1.12352718]
 [ 0.2945583  -0.91129765 -0.94405591 -0.54364489 -1.40280509]
 [ 0.89711507  1.08340474 -0.16329415  0.28493368 -1.06291461]
 [-0.29352082  1.31741072  0.14345898  1.46976536 -1.69543079]
 [ 0.88594726 -0.12330785  0.72781183 -1.9717379   0.29715511]]


2. DIVISIBLE BY 3 PROBLEM: Create the following 10 x 10 ndarray.
\
A = \begin{bmatrix}
1 & 4 & \cdots & 81 & 100 \\
\vdots & \vdots & \ddots & \vdots & \vdots \\
\vdots & \vdots & \ddots & \vdots & \vdots \\
\vdots & \vdots & \ddots & \vdots & \vdots \\
8281 & 8464 & \cdots & 9801 & 10000
\end{bmatrix}


which are the squares of the first 100 positive integers.  

From this ndarray, determine all the elements that are divisible by 3. Save the result as **div_by_3.npy**.


In [5]:
# Import numpy library as np
import numpy as np

# Create an array of integers from 1 to 100
numbers = np.arange(1, 101)

# Square each integer to get the squares of the first 100 positive integers
squares = numbers**2

# Reshape the 1D array of 100 squares into a 10x10 matrix
A = squares.reshape(10, 10)

# Select all elements in A that are divisible by 3
div_by_3 = A[A % 3 == 0]

# Save the elements divisible by 3 into a file named 'div_by_3.npy'
np.save("div_by_3.npy", div_by_3)

# Display the 10x10 matrix of squares
print("Matrix A (squares of first 100 positive integers):\n", A)

# Display only the elements that are divisible by 3
print("\nElements divisible by 3:\n", div_by_3)

Matrix A (squares of first 100 positive integers):
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
